- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 37f8d0f5-68fd-4e27-b5a8-90f2c3ddda10
  loglevel: INFO
  name: prod-job
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/sh

        echo 'prod'
    keepgoing: false
    strategy: node-first
  uuid: 37f8d0f5-68fd-4e27-b5a8-90f2c3ddda10

